### ISSUE TITLE
fail to generate certificate and key when provider is set to certmonger.

### ISSUE THREAD

**Issue by amore17** [linux-system-roles/certificate#21]
certificate_requests:
      - name: /tmp/mycertTC20
        dns: www.example.com
        ca: self-sign
        provider: certmonger

`ansible-playbook tests/tests_provider_cert.yml`
` ls -ll /tmp/mycertTC20.crt`
ls: cannot access '/tmp/mycertTC20.crt': No such file or directory
`ls -ll /tmp/mycertTC20.key`
ls: cannot access '/tmp/mycertTC20.key': No such file or directory

**Comment by pcahyna** [comment]
@amore17 please enclose outputs from running commands between ``` lines to avoid formatting, like,
```
$ echo foo
foo
```

**Comment by seocam** [comment]
@amore17 could you send me the exact playbook you are playing? What's the OS you are currently running the tests on?
Just tried on CentOS 8.1 and I could not reproduce it.

**Comment by amore17** [comment]
@seocam It was my environment setup issue.
Closing it, Sorry for inconvenience.

**Comment by seocam** [comment]
np! thanks @amore17
