### ISSUE TITLE
Add support to Debian 9

### ISSUE THREAD

**Issue by seocam** [linux-system-roles/certificate#4]
So far the tests have been executed only on Debian 10. We need to test and fix what's needs to ensure it also runs on Debian 9.

**Comment by jh23453** [comment]
Since Debian 11 has been released it would be nice to get in supported as well.
I've changed roles/certificate/vars/Debian.yml:
```
__certificate_packages:
  - python3-pyasn1
  - python3-cryptography
  - python3-dbus
```
My guess is that a rename Debian.yml -> Debian_10.yml should work.
What must change for Debian 9?

**Comment by rjeffman** [comment]
As of August 2022, Debian 9 "stretch" is EOL, therefore, I'm closing this issue.

If you have any reason so that this should be reopened, please reopen it and provide the reasons in a comment.
