### ISSUE TITLE
Issuing certs out of /etc/pki/tls/ is not working when selinux is enabled

### ISSUE THREAD

**Issue by seocam** [linux-system-roles/certificate#5]
Currently issuing certs using certmonger provider in any location out of  `/etc/pki/tls/` is not working when selinux is enforced.

https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-certificate-pull-linux-system-roles_certificate-3-4c9f24e-centos-7-20200601-115725/artifacts/test.log.html

**Comment by richm** [comment]
role recommends to use selinux system role to mitigate issues like this
