### ISSUE TITLE
Error running ipa test - ImportError: cannot import name IPA_MODULES

### ISSUE THREAD

**Issue by richm** [linux-system-roles/certificate#60]
I get this running tests_basic_ipa.yml
```
ImportError: cannot import name 'IPA_MODULES' from 'ipaserver.install.installutils' (/usr/lib/python3.8/site-packages/ipaserver/install/installutils.py)^M
```
I think this has been fixed in ansible-freeipa v0.2.0 - I think the tests needs to install v0.2.0 at https://github.com/linux-system-roles/certificate/blob/master/tests/tasks/setup_ipa.yml#L15

@mprovenc

**Comment by richm** [comment]
Here is how v0.2.0 fixed the issue - https://github.com/freeipa/ansible-freeipa/blob/v0.2.0/roles/ipaserver/module_utils/ansible_ipa_server.py#L133

**Comment by rjeffman** [comment]
I'm closing this issue, as it was fixed by updating ansible-freeipa version.

If you think the solution is not satisfactory, please reopen it.
