### ISSUE TITLE
ipa test should install the hostname command

### ISSUE THREAD

**Issue by richm** [linux-system-roles/certificate#81]
setup_ipa.yml uses the `hostname` module: https://github.com/linux-system-roles/certificate/blob/master/tests/tasks/setup_ipa.yml#L34
The module requires the `hostname` command.  This is not installed on all platforms.  The test should install the package providing the command.  This is the cause of the `rhel-x` test failures.

**Comment by rjeffman** [comment]
After PR #183 was merged, `hostname` strategy was changed to `systemd`. Is it enough to close this issue?

**Comment by richm** [comment]
> After PR #183 was merged, `hostname` strategy was changed to `systemd`. Is it enough to close this issue?

Yes- thanks!
