### ISSUE TITLE
`ca: SelfSign` certificates don't validate in RHEL/CentOS 7

### ISSUE THREAD

**Issue by martinpitt** [linux-system-roles/certificate#99]
As part of https://github.com/linux-system-roles/cockpit/pull/39 I am debugging why `ca: self-signed` certificates don't work properly on RHEL/CentOS 7. The first hurdle is issue #98, but that can be worked around easily. But then, these certificates are not accepted as CA. I created it with
```
    - include_role:
        name: linux-system-roles.certificate
      vars:
        certificate_requests:
          - name: monger-cockpit
            dns: ['localhost', 'www.example.com']
            # "self-sign" does not work: https://github.com/linux-system-roles/certificate/issues/98
            ca: SelfSign
            group: cockpit-ws
```

This generates a certificate with these properties:
```
# openssl x509 -in /etc/pki/tls/certs/monger-cockpit.crt -text
        X509v3 extensions:
            X509v3 Key Usage:
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name:
                DNS:localhost, DNS:www.example.com
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
```

But curl/OpenSSL do not accept this as CA:
```
# openssl s_server -cert /etc/pki/tls/certs/monger-cockpit.crt -key /etc/pki/tls/private/monger-cockpit.key 

# openssl s_client -CAfile /etc/pki/tls/certs/monger-cockpit.crt -verify 1 -verify_return_error -connect localhost:4433 </dev/null 
```
The latter says
```
verify depth is 1
CONNECTED(00000003)
depth=0 CN = localhost
verify error:num=20:unable to get local issuer certificate
140342795151248:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264:
```
and the former (server end) logs
```
ERROR
139809968650128:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:s3_pkt.c:1493:SSL alert number 48
shutting down SSL
CONNECTION CLOSED
```

The same happens with curl:
```
 port 4433 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 4433 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/monger-cockpit.crt
  CApath: none
* Server certificate:
* 	subject: CN=localhost
* 	start date: Oct 20 12:00:32 2021 GMT
* 	expire date: Oct 20 12:00:32 2022 GMT
* 	common name: localhost
* 	issuer: CN=localhost
* NSS error -8156 (SEC_ERROR_CA_CERT_INVALID)
* Issuer certificate is invalid.
* Closing connection 0
curl: (60) Issuer certificate is invalid.
```

At first I thought this would be due to a too restrictive "Key Usage". However, for some reason this works on Fedora/RHEL 8, even though the generated KU/EKU fields are the same. But OpenSSL and curl accept the .crt as CA with no problem.

If I manually request a certificate with the default properties:

    # getcert request -c SelfSign -f /etc/pki/tls/certs/my.crt -k /etc/pki/tls/private/my.key -D localhost

it has different KU/EKU:
```
            X509v3 Subject Alternative Name: 
                DNS:rhel-7-9-127-0-0-2-2201
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
```

and I can use the same server/client commands (with the different cert path), and it works a little better:
```
# openssl s_server -cert /etc/pki/tls/certs/my.crt -key /etc/pki/tls/private/my.key
# openssl s_client -CAfile /etc/pki/tls/certs/my.crt -verify 1 -verify_return_error -connect localhost:4433 </dev/null 
verify depth is 1
CONNECTED(00000003)
depth=0 CN = rhel-7-9-127-0-0-2-2201
verify return:1
---
Certificate chain
 0 s:/CN=rhel-7-9-127-0-0-2-2201
   i:/CN=rhel-7-9-127-0-0-2-2201
```

However, `curl` is still unhappy and rejects it. I tried to generate it with more usage types like `-u digitalSignature -u dataEncipherment -u keyAgreement -ukeyCertSign`, but that doesn't seem to help.

I did not track this down further so far, as it's probably moot? Supposedly l-s-r won't change much any more in RHEL 7, I just want to document this a little for referring from workarounds.

**Comment by orodbhen** [comment]
Not sure if this is related, but this role doesn't seem to work at all in CentOS 7. The playbook completes without errors, but skips most of the tasks, and no certificates are created. Tried both IPA and self-sign CAs. I'm not able to copy and paste the output into here, but the settings are pretty basic. Should I not expect this to work on CentOS 7?

Note that `certmonger` run outside of ansible works as expected.

**Comment by richm** [comment]
> Not sure if this is related, but this role doesn't seem to work at all in CentOS 7. The playbook completes without errors, but skips most of the tasks, and no certificates are created. Tried both IPA and self-sign CAs. I'm not able to copy and paste the output into here, but the settings are pretty basic. Should I not expect this to work on CentOS 7?
> 
> Note that `certmonger` run outside of ansible works as expected.

What version of the certificate role are you using?  What version of centos7 (if not the latest)?  What is your inventory that you are using?

@rjeffman any ideas?

**Comment by rjeffman** [comment]
No ideas right now.

I'll look at this tomorrow, as I'm leaving early today, and I'm rebuilding my CentOS/REHL 7 testing environment.

**Comment by orodbhen** [comment]
> > Not sure if this is related, but this role doesn't seem to work at all in CentOS 7. The playbook completes without errors, but skips most of the tasks, and no certificates are created. Tried both IPA and self-sign CAs. I'm not able to copy and paste the output into here, but the settings are pretty basic. Should I not expect this to work on CentOS 7?
> > Note that `certmonger` run outside of ansible works as expected.
> 
> What version of the certificate role are you using? What version of centos7 (if not the latest)? What is your inventory that you are using?
> 
> @rjeffman any ideas?

We just pulled in the latest patches this morning, and rhel-system-roles was updated to 1.21.2. So I'll try again and see if it's made a difference.

**Comment by orodbhen** [comment]
It was at 1.7.3 before.

**Comment by orodbhen** [comment]
No difference for 1.21.2. I'm using a plugin that gets the inventory from IPA.

**Comment by orodbhen** [comment]
Nevermind. I had `certificate_request` instead of `certificate_requests`. It's still not working, though, but I'm at least getting error messages now.

**Comment by orodbhen** [comment]
The IPA CA didn't like `email` being set for a service certificate. It's working now. Thanks.

**Comment by richm** [comment]
> The IPA CA didn't like `email` being set for a service certificate. It's working now. Thanks.

ok - closing
